---
abstract: 'Manipulate 128 bits integers in Perl'
author:
  - 'Salvador Fandino <sfandino@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-Int128
no_index:
  directory:
    - t
    - inc
requires:
  Math::Int64: '0.34'
resources:
  repository: https://github.com/salva/p5-Math-Int128
version: 0.16_02
