---
abstract: 'Manipulate 128 bits integers in Perl'
author:
  - 'Salvador Fandino <sfandino@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Int128
no_index:
  directory:
    - t
    - inc
requires:
  Math::Int64: 0.27_04
version: 0.07
